name: myapp
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=ng1n3
    #   - MONGO_INITDB_ROOT_PASSWORD=123456
    env_file:
      - ./mongo.env
    # networks:
    #   - goals-net 
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true 
    depends_on:
      - backend
# only for named volume
volumes:
  data:
  logs: